### ISSUE TITLE
threads panic and said 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by jblueberry** [schelterlabs/hedgecut#1]
When I run script `evaluate_accuracy_forget`, threads for trees will panic and said:
```bash
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/junhui/new/hedgecut/src/tree.rs:308:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My server is Ubuntu 20.04.4, my Rust version is `1.63.0` and here are the steps of my command:

```bash
git clone https://github.com/schelterlabs/hedgecut.git
cd hedgecut
python3 python/prepare_adult.py
cargo run --bin evaluate_accuracy_forget
```

In addition to `adult` data, I also did tests on `givemesomecredit` and `cardio`. They all occur with this 'attempt to subtract with overflow' error.

I have tried many times and it seemed that the problem was at [this line](https://github.com/schelterlabs/hedgecut/blob/10e093a638b7b9f8875e98b58f7da89027e19138/src/tree.rs#L277) and [this line](https://github.com/schelterlabs/hedgecut/blob/10e093a638b7b9f8875e98b58f7da89027e19138/src/tree.rs#L308). They are both caused when a tree tries to forget a sample and find an leaf element via this sample, and try to minus a zero variable by one.

Hope you can answer my question in your busy schedule, thank you.

**Comment by sscdotopen** [comment]
Hi,

I reran the code on my machine and did not encounter these errors (there might still be a bug somewhere though). 

Could try to run the experiment as outlined in [experiments_accuracy_forget.fish](https://github.com/schelterlabs/hedgecut/blob/master/experiments_accuracy_forget.fish), e.g., with the following command:

`RUSTFLAGS="-C target-cpu=native" cargo run --release --bin evaluate_accuracy_forget`

I will try to take a deeper look next week.

**Comment by jblueberry** [comment]
Thank you for your reply in your busy schedule.

I just tried the command you provided and found that the program will not panic if you add a `--release` flag in the command.

More specifically,
```bash
RUSTFLAGS="-C target-cpu=native" cargo run --release --bin evaluate_accuracy_forget
```
will not panic, **but**
```bash
RUSTFLAGS="-C target-cpu=native" cargo run --bin evaluate_accuracy_forget
```
will panic at [this line](https://github.com/schelterlabs/hedgecut/blob/10e093a638b7b9f8875e98b58f7da89027e19138/src/tree.rs#L277) and [this line](https://github.com/schelterlabs/hedgecut/blob/10e093a638b7b9f8875e98b58f7da89027e19138/src/tree.rs#L308).

Then I want to make sure that the behavior of the program is the same in both compilation modes above. I add a `assert!` macro in [this line](https://github.com/schelterlabs/hedgecut/blob/10e093a638b7b9f8875e98b58f7da89027e19138/src/tree.rs#L277), like:

```rust
let new_num_samples = num_samples - 1;
    let new_num_plus = if sample.true_label() {
        assert!(*num_plus > 0, "going to overflow"); // new assert to panic when an overflow is going to happen
        *num_plus - 1
    } else {
        *num_plus
    };
```

After editing, the program will also panic by the `assert!` in the `release` mode. Here is the shell output:

```bash
thread 'thread '<unnamed><unnamed>thread '' panicked at 'going to overflowthread '<unnamed>thread '', thread '' panicked at '<unnamed>thread '' panicked at 'thread 'thread '<unnamed>thread 'thread 'thread '<unnamed>/home/junhui/new/hedgecut/src/tree.rsgoing to overflow' panicked at '', going to overflow<unnamed>thread '<unnamed><unnamed>' panicked at 'thread '<unnamed><unnamed><unnamed>' panicked at '<unnamed>:going to overflow', /home/junhui/new/hedgecut/src/tree.rsthread '/home/junhui/new/hedgecut/src/tree.rsthread '' panicked at '' panicked at '' panicked at 'going to overflow<unnamed>' panicked at '' panicked at 'going to overflow277', :<unnamed>' panicked at ':going to overflow' panicked at 'going to overflowgoing to overflow', <unnamed>', ' panicked at 'going to overflowthread '', :/home/junhui/new/hedgecut/src/tree.rs277going to overflow' panicked at '', going to overflow', /home/junhui/new/hedgecut/src/tree.rs' panicked at '/home/junhui/new/hedgecut/src/tree.rs<unnamed>', /home/junhui/new/hedgecut/src/tree.rs25:going to overflow:', going to overflowgoing to overflow/home/junhui/new/hedgecut/src/tree.rs', /home/junhui/new/hedgecut/src/tree.rsgoing to overflow:::/home/junhui/new/hedgecut/src/tree.rs27725/home/junhui/new/hedgecut/src/tree.rs', ', :/home/junhui/new/hedgecut/src/tree.rs:', 277277::277
:/home/junhui/new/hedgecut/src/tree.rs/home/junhui/new/hedgecut/src/tree.rs277:277/home/junhui/new/hedgecut/src/tree.rs::27725:note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
277:::277::2525:
25:27727725:25277

25
25::
25277
:
' panicked at '

2525
:25', 

25

going to overflow/home/junhui/new/hedgecut/src/tree.rs:277', /home/junhui/new/hedgecut/src/tree.rs:277:25:
25
thread '<unnamed>' panicked at 'going to overflow', /home/junhui/new/hedgecut/src/tree.rs:277:25
```

The output of the terminal is confusing because there are many threads panic at the same time. And we can conclude that there  is still integer overflow happening in the program, but release mode just ignores them.

**Comment by sscdotopen** [comment]
Yes, there might still be overflows, that's why I said there might still be bugs even though the program runs correctly with this command. I will take a deeper look next week on why this is happening, my suspicion is that some tree variants might not be correctly updated in certain situations. I think the assert should check for num_plus >= 0 though.

**Comment by sscdotopen** [comment]
I found a one-off error during the swapping of the elements after splitting, this commit https://github.com/schelterlabs/hedgecut/commit/050a2b49a295d17c0893fd3c557fbabdd496d6a6 should have fixed it.
